services:
  redis:
    container_name: 'some-redis'
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - redis-net

  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
